export const FETCH_CITIES_STARTED = 'FETCH_CITIES_STARTED';
export const FETCH_CITIES_FAILED = 'FETCH_CITIES_FAILED';
export const FETCH_CITIES_SUCCEEDED = 'FETCH_CITIES_SUCCEEDED';
export const FETCH_TRIPS_SUCCEEDED = 'FETCH_TRIPS_SUCCEEDED';
